script: bash ./deploy.sh
language: node_js
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '6'
env:
  global:
    - GH_REF: github.com/TondaHack/react-stack.git
    - secure: "pzoGS05TY6awxVTUiuux5AqRYiug1LTu0xsj7oorxMg7QPByKXaHppXto6HdrQ9f1qq6ubGaYfjqOEyoSLRLk7QwddnnqL7TZ5JlOHzHW8oYcmg0d0SCEVcAZlyRSoKmqa6YkkF60Soi1p82p4YFd7gaFbpzwz0N/vCmWR4g7ufG8kCqzm7yOQd0rCAHEzKArHqGAF9Q/KCUEVPkaFZiDeCvdcpvb2sNyLM1GA73NEtrS4gfWvS7TK9k6qpiJzCEvbYe+CEslme1MLXPAQKrWuxilJ7I0mekiM4aUbdvJLtgzdBu112A7x5HUdCe3iHUJMjpL0qo/SCKh96pi+7ROkYLWn9lxl7bv6BoLjiwhZawMKL/ndptbCcWHI3Gd39+dmJIXzrr3hdAGPgmcT0fv0ov057lot/vz4oTv+Wfhp34eau+BsdxlNq/qgho7dXFRpY+ghU5Y1KXurUVdKXdDukOcFwIDfTwQJ91/xlqo46OdmRNFU0i6M0U1u0TxJgFjiT9S4u6++oB7KjKNDzgHhC0RSVyVBGnEv786mSDzEVQH4jbjclhwjQ1is09zztki9yRBwn+FDdkBFJRI8JBHdYrYEODm1OHpToPw/Ysi8na+eumywFIdCplv8y2GHAhWu1a0I9Iw8Kpla9yfP1yde3tMzjAr2ZzziU7hD9sWWI="
branches:
  except:
    - gh-pages
  only:
    - master
